# Generated by Django 2.2.6 on 2019-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_merchant', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('link_gambar', models.CharField(max_length=200)),
            ],
        ),
    ]
