# Generated by Django 2.2.6 on 2019-10-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='Satisfaction',
            field=models.IntegerField(),
        ),
    ]
