dist: xenial
language: python
python:
    - "3.7"
jobs:
  include:
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: $HEROKU_APP_NAME
        api_key: $HEROKU_API_KEY
        run:
          - python manage.py migrate