dist: xenial
language: python
python:
    - "3.7"

jobs:
  include:
    - stage: test
      before_script:
        - gem install dpl
        - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      script:
        - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
        - export HEROKU_API_KEY=$HEROKU_APIKEY
        - heroku run --app $HEROKU_APPNAME migrate
    - stage: deploy
      script: skip
      deploy: &heroku
        provider: heroku
        app: $HEROKU_APP_NAME
        api_key: $HEROKU_API_KEY
        run:
          - python manage.py migrate